apiVersion: v1
kind: Service
metadata:
  name: game-engine-service
  namespace: burja
spec:
  type: ClusterIP
  selector:
    app: game-engine-service
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
  - name: grpc
    port: 50052
    targetPort: 50052
    protocol: TCP
