/* eslint-disable */
/*
  AUTO-GENERATED FILE
  Generated by: scripts/generate-lucide-icon-nodes.mjs
  Do not edit by hand.
*/

export type LucideIconNode = Array<[string, Record<string, string>]>;

export const CLUB_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z",
      "key": "27yuqz"
    }
  ],
  [
    "path",
    {
      "d": "M12 17.66L12 22",
      "key": "ogfahf"
    }
  ]
];

export const CROWN_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z",
      "key": "1vdc57"
    }
  ],
  [
    "path",
    {
      "d": "M5 21h14",
      "key": "11awu3"
    }
  ]
];

export const DIAMOND_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M2.7 10.3a2.41 2.41 0 0 0 0 3.41l7.59 7.59a2.41 2.41 0 0 0 3.41 0l7.59-7.59a2.41 2.41 0 0 0 0-3.41l-7.59-7.59a2.41 2.41 0 0 0-3.41 0Z",
      "key": "1f1r0c"
    }
  ]
];

export const FLAG_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z",
      "key": "i9b6wo"
    }
  ],
  [
    "line",
    {
      "x1": "4",
      "x2": "4",
      "y1": "22",
      "y2": "15",
      "key": "1cm3nv"
    }
  ]
];

export const HEART_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z",
      "key": "c3ymky"
    }
  ]
];

export const SPADE_ICON_NODE: LucideIconNode = [
  [
    "path",
    {
      "d": "M5 9c-1.5 1.5-3 3.2-3 5.5A5.5 5.5 0 0 0 7.5 20c1.8 0 3-.5 4.5-2 1.5 1.5 2.7 2 4.5 2a5.5 5.5 0 0 0 5.5-5.5c0-2.3-1.5-4-3-5.5l-7-7-7 7Z",
      "key": "40bo9n"
    }
  ],
  [
    "path",
    {
      "d": "M12 18v4",
      "key": "jadmvz"
    }
  ]
];

export const LUCIDE_ICON_NODES_BY_SYMBOL: Record<string, LucideIconNode> = {
  "club": CLUB_ICON_NODE,
  "crown": CROWN_ICON_NODE,
  "diamond": DIAMOND_ICON_NODE,
  "flag": FLAG_ICON_NODE,
  "heart": HEART_ICON_NODE,
  "spade": SPADE_ICON_NODE,
};
